version: "3.9"
services:
  redis-server:
    image: "redis"
    restart: always

  #notifier-service:
  #  build:
  #    context: ../
  #    dockerfile: DistributedSystems/DistributedSystems.NotifierService/Dockerfile
  #  restart: always
  #  depends_on:
  #    - redis-server

  flight-service:
    build:
      context: ../
      dockerfile: DistributedSystems/DistributedSystems.FlightsService/Dockerfile
    restart: always
    depends_on:
      - redis-server

  web-service:
    build:
      context: ../
      dockerfile: DistributedSystems/DistributedSystems.Web/Dockerfile
    restart: always
    ports:
      - "8187:80"
    depends_on:
      - flight-service
      - redis-server
    