version: "3"
services:
  redis-server:
    image: "redis"
    restart: always

  notifier-service:
    build:
      context: ./
      dockerfile: DistributedSystems.NotifierService/Dockerfile
    restart: always
    environment:
      - REDIS_SERVER_HOST=redis-server
    depends_on:
      - redis-server

  flight-service:
    build:
      context: ./
      dockerfile: DistributedSystems.FlightsService/Dockerfile
    restart: always
    environment:
      - GRPC_SERVER_PORT=30051

  web-service:
    build:
      context: ./
      dockerfile: DistributedSystems.Web/Dockerfile
    restart: always
    ports:
      - "8187:80"
    environment:
      - GRPC_SERVER_PORT=30051
      - GRPC_SERVER_HOST=flight-service
      - REDIS_SERVER_HOST=redis-server
    depends_on:
      - flight-service
      - redis-server
    